server:
  port: 8980
spring:
  application:
    name: walk_server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.13.4.248:3306/datastorm?allowMutiQueries=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
    username: root
    password: Fhl0009252937#
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      max-lifetime: 12
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.code.server.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    default-fetch-size: 1000
  global-config:
    db-config:
      id-type: auto
pagehelper:
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect 属性来指定分页插件使用哪种方言。
  helper-dialect: mysql
  #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页。
  reasonable: true
  #支持通过Mapper接口参数传递page参数,默认值为false
  support-methods-arguments: true
  #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页)
  page-size-zero: true
  #为了支持 startPage(Object params) 方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
